/**
* File: FrmCostCalc.java
* Version: 1.0
* Author: Ajitesh Nagarajan
* Date: July 08 2021
* Description: This is a program with a UI than will calculate the amount of money you will need to pay if you buy certain drinks at this virtual drink bar I made up.
*/
public class FrmCostCalc extends javax.swing.JFrame {

    /**
     * Creates new form FrmCostCalc
     */
    public FrmCostCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblLemonade = new javax.swing.JLabel();
        lblStrawberryBananna = new javax.swing.JLabel();
        txtLemonade = new javax.swing.JTextField();
        txtStrawberryBanana = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblFinalPrice = new javax.swing.JLabel();
        lblAppleJuice = new javax.swing.JLabel();
        lblOrangeJuice = new javax.swing.JLabel();
        lblMango = new javax.swing.JLabel();
        txtAppleJuice = new javax.swing.JTextField();
        txtMango = new javax.swing.JTextField();
        txtOrangeJuice = new javax.swing.JTextField();
        lblSubCost = new javax.swing.JLabel();
        lblTaxCost = new javax.swing.JLabel();
        lblFinalPriceCost = new javax.swing.JLabel();
        lblTitleName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        lblTitleName1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLemonade.setText("Lemonade ($5.25)");

        lblStrawberryBananna.setText("Strawberry Banana ($5.75)");

        txtLemonade.setText("0");
        txtLemonade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLemonadeActionPerformed(evt);
            }
        });

        txtStrawberryBanana.setText("0");
        txtStrawberryBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStrawberryBananaActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblSubtotal.setText("Subtotal: ");

        lblTaxes.setText("Taxes (13%):");

        lblFinalPrice.setText("Final Price:");

        lblAppleJuice.setText("Apple Juice ($5)");

        lblOrangeJuice.setText("Orange Juice ($5)");

        lblMango.setText("Mango ($5.75)");

        txtAppleJuice.setText("0");
        txtAppleJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppleJuiceActionPerformed(evt);
            }
        });

        txtMango.setText("0");
        txtMango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMangoActionPerformed(evt);
            }
        });

        txtOrangeJuice.setText("0");
        txtOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrangeJuiceActionPerformed(evt);
            }
        });

        lblSubCost.setText("$0 ");

        lblTaxCost.setText("$0 ");

        lblFinalPriceCost.setText("$0 ");

        lblTitleName.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        lblTitleName.setText("Drakes Drink Bar");

        lblDescription.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDescription.setText("You can pick out the number of drinks you would like to order right below");

        lblDescription1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDescription1.setText(" and the subtotal, total and final price will be calculated for you to see.");

        lblTitleName1.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N

        image.setFont(new java.awt.Font("Krungthep", 0, 36)); // NOI18N
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_3drink.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitleName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblTitleName))
                            .addComponent(lblDescription)
                            .addComponent(lblDescription1))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStrawberryBananna)
                            .addComponent(lblLemonade)
                            .addComponent(lblAppleJuice)
                            .addComponent(lblOrangeJuice)
                            .addComponent(lblMango))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLemonade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStrawberryBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAppleJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMango, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinalPrice)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSubtotal)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblSubCost))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTaxes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinalPriceCost)
                                    .addComponent(lblTaxCost))))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitleName)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescription)
                        .addGap(0, 0, 0)
                        .addComponent(lblDescription1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitleName1))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLemonade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLemonade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStrawberryBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStrawberryBananna))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAppleJuice)
                            .addComponent(txtAppleJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrangeJuice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMango))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(lblSubCost))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaxes)
                            .addComponent(lblTaxCost))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinalPrice)
                            .addComponent(lblFinalPriceCost))
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLemonadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLemonadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLemonadeActionPerformed

    private void txtStrawberryBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStrawberryBananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStrawberryBananaActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
       final double LEMONADE_COST = 5.25; //Lemonade cost                           //declare variables
       final double STRAWBERRY_BANANA_COST = 5.75; //Strawberry Banana drink cost
       final int APPLE_JUICE_COST = 5;  //Apple Juice cost
       final int ORANGE_JUICE_COST = 5; //Orange Juice cost
       final double MANGO_COST = 5.75; //Mango drink cost
       int LemonadeQuantity; //Quantity of Lemonade user asks for
       int StrawberryBananaQuantity; //Quantity of Strawberry Banana drink user asks for
       int AppleJuiceQuantity; //Quantity of Apple Juice user asks for
       int OrangeJuiceQuantity; //Quantity of Orange Juice user asks for
       int MangoQuantity; //Quantity of Mango drink user asks for
       double LemonadeTotal; //Total cost for all Lemonades
       double StrawberryBananaTotal; //Total cost for all Strawberry Banana drinks
       int AppleJuiceTotal; //Total cost for all Apple juices
       int OrangeJuiceTotal; //Total cost for all Orange juices
       double MangoTotal; //Total cost for all Mango drinks
       double Subtotal; //Total cost for all drinks
       double Taxes; //Taxes
       double Final; //Final Cost
       double TaxesR; //Taxes*100 and rounded
       double FinalR; //Final cost*100 and rounded
       
       LemonadeQuantity = Integer.parseInt(txtLemonade.getText()); //User inputted Quantity of Lemonades
       StrawberryBananaQuantity = Integer.parseInt(txtStrawberryBanana.getText());  //User inputted Quantity of Strawberry Banana drinks
       AppleJuiceQuantity = Integer.parseInt(txtAppleJuice.getText());  //User inputted Quantity of Apple Juices
       OrangeJuiceQuantity = Integer.parseInt(txtOrangeJuice.getText());  //User inputted Quantity of Orange Juices
       MangoQuantity = Integer.parseInt(txtMango.getText());  //User inputted Quantity of Mango drinks
       
       LemonadeTotal = LemonadeQuantity * LEMONADE_COST;//calculated cost for lemonades
       StrawberryBananaTotal = StrawberryBananaQuantity * STRAWBERRY_BANANA_COST;//calculated cost for Strawberry banana drinks
       AppleJuiceTotal = AppleJuiceQuantity * APPLE_JUICE_COST; //calculated cost for Apple juices
       OrangeJuiceTotal = OrangeJuiceQuantity * ORANGE_JUICE_COST; //calculated cost for Orange Juices
       MangoTotal = MangoQuantity * MANGO_COST; //calculated cost for Mango drinks
       
       Subtotal = LemonadeTotal + StrawberryBananaTotal + AppleJuiceTotal + OrangeJuiceTotal + MangoTotal; //Subtotal Calculation
       lblSubCost.setText("$"+String.valueOf(Subtotal)); //Subtotal output
       
       Taxes = Subtotal * 0.13; //Taxes Calculations
       TaxesR = (Math.round(Taxes*100)); //Rounding Taxes (multiplying by 100)
       lblTaxCost.setText("$"+String.valueOf(TaxesR/100)); //Taxes Output (dividing by 100)
       
       Final = Subtotal + Taxes; //The Final cost calculation
       FinalR = (Math.round(Final*100)); //Rounding Final cost(multiplying by 100)
       lblFinalPriceCost.setText("$"+String.valueOf(FinalR/100)); //Final cost output (dividing by 100)
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtAppleJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppleJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppleJuiceActionPerformed

    private void txtMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMangoActionPerformed

    private void txtOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrangeJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrangeJuiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCostCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCostCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCostCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCostCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCostCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblAppleJuice;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblFinalPriceCost;
    private javax.swing.JLabel lblLemonade;
    private javax.swing.JLabel lblMango;
    private javax.swing.JLabel lblOrangeJuice;
    private javax.swing.JLabel lblStrawberryBananna;
    private javax.swing.JLabel lblSubCost;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTaxCost;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTitleName;
    private javax.swing.JLabel lblTitleName1;
    private javax.swing.JTextField txtAppleJuice;
    private javax.swing.JTextField txtLemonade;
    private javax.swing.JTextField txtMango;
    private javax.swing.JTextField txtOrangeJuice;
    private javax.swing.JTextField txtStrawberryBanana;
    // End of variables declaration//GEN-END:variables
}
